using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.UI;
using System.Runtime.Serialization;
using System.Collections.Specialized;
using System.Text;

namespace WebApplication2
{
    public partial class _Default : Page
    {
        //global variables set in a class of their own
        //so when one is updated it stays updated
        //this is the requierment for any web application 
        public static class globals
        {
            public static int secret = 0;
            public static int attempts = 0;
        }
        //default page load
        protected void Page_Load(object sender, EventArgs e)
        {
         
        }

        //generate random number button push
        protected void Button1_Click(object sender, EventArgs e)
        {
            //this create our base address which we will append to later to access methods in the RESTful service
            Uri baseUri = new Uri("http://localhost:46791/Service1.svc");

            //this creates the template that will be added later to access the RESTful service
            UriTemplate temp = new UriTemplate("/get?lowerB={lower}&upperB={upper}");

            //this  associate the values with the correct variables in the uri
            NameValueCollection parameters = new NameValueCollection();
            parameters.Add("lower", TextBox1.Text);
            parameters.Add("upper", TextBox2.Text);
            Uri namedUri = temp.BindByName(baseUri, parameters);

            
            // this allows to recieve incoming data from the website
            WebClient client = new WebClient();

            //check if the two box have been filled in
            if (TextBox1.Text != "" && TextBox2.Text != "")
            {

                // get the specified information from the webpage and store it in a byte array for processing
                byte[] data = client.DownloadData(namedUri);

                //  this converts the data into a memory stream for processing
                Stream mem = new MemoryStream(data);

                //this is for deserialization of the XML data that is recieved in int form
                DataContractSerializer serial = new DataContractSerializer(typeof(int));

                //secret number generated by the NumberGuess class
                globals.secret = Convert.ToInt32(serial.ReadObject(mem));

                //the secret number has been generated now we assume the
                //player starts guessing after so we will set the attempts to 0
                TextBox4.Text = Convert.ToString(globals.attempts);

                //let the user know the secret number has been generate
                ClientScript.RegisterStartupScript(this.GetType(), "myalert", "alert('" + "the secret number has been generated please enter a guess" + "');", true);
            }

            //catch the user not entering any data
            else
            {
                //let the user know they need to enter a lower and upper bound
                ClientScript.RegisterStartupScript(this.GetType(), "myalert", "alert('" + "please enter a lower and upper bound" + "');", true);
            }
        }

        //play button pushed
        protected void Button2_Click(object sender, EventArgs e)
        {
            
            //this create our base address which we will append to later to access methods in the RESTful service
            Uri baseUri = new Uri("http://localhost:46791/Service1.svc");

            //this creates the template that will be added later to access the RESTful service
            UriTemplate temp = new UriTemplate("/check?UserNum={userNum}&SecretNum={SecretNum}");

            //this helps associate the values with the correct variables in the uri
            NameValueCollection parameters = new NameValueCollection();
            parameters.Add("userNum", TextBox3.Text);
            parameters.Add("SecretNum", Convert.ToString(globals.secret));
            Uri namedUri = temp.BindByName(baseUri, parameters);

            // this allows to recieve incoming data from the website
            WebClient client = new WebClient();

            //check to make sure the guess box is not empty
            if (TextBox3.Text != "")
            {
                //user has pushed the play button so update the number of attempts and assign it to the textbox
                globals.attempts++;
                TextBox4.Text = Convert.ToString(globals.attempts);

                // get the specified information from the webpage and store it in a byte array for processing
                byte[] data = client.DownloadData(namedUri);

                //  this converts the data into a memory stream for processing
                var mem = new MemoryStream(data);

                //this is for deserialization of the XML data that is recieved in string form
                DataContractSerializer obj = new DataContractSerializer(typeof(String));

                //output the result of the guess to the textbox
                TextBox5.Text = Encoding.ASCII.GetString(mem.ToArray());
            }

            //catch user not entering data
            else
            {
                //let the user know to make a guess
                ClientScript.RegisterStartupScript(this.GetType(), "myalert", "alert('" + "please enter a guess for the secret number" + "');", true);
            }
        }
    }
}