//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace numWinForm.myService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="myService.ImyService")]
    public interface ImyService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ImyService/SecretNumber", ReplyAction="http://tempuri.org/ImyService/SecretNumberResponse")]
        int SecretNumber(int lower, int upper);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ImyService/SecretNumber", ReplyAction="http://tempuri.org/ImyService/SecretNumberResponse")]
        System.Threading.Tasks.Task<int> SecretNumberAsync(int lower, int upper);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ImyService/checkNumber", ReplyAction="http://tempuri.org/ImyService/checkNumberResponse")]
        string checkNumber(int userNum, int SecretNum);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ImyService/checkNumber", ReplyAction="http://tempuri.org/ImyService/checkNumberResponse")]
        System.Threading.Tasks.Task<string> checkNumberAsync(int userNum, int SecretNum);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ImyServiceChannel : numWinForm.myService.ImyService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ImyServiceClient : System.ServiceModel.ClientBase<numWinForm.myService.ImyService>, numWinForm.myService.ImyService {
        
        public ImyServiceClient() {
        }
        
        public ImyServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ImyServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ImyServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ImyServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int SecretNumber(int lower, int upper) {
            return base.Channel.SecretNumber(lower, upper);
        }
        
        public System.Threading.Tasks.Task<int> SecretNumberAsync(int lower, int upper) {
            return base.Channel.SecretNumberAsync(lower, upper);
        }
        
        public string checkNumber(int userNum, int SecretNum) {
            return base.Channel.checkNumber(userNum, SecretNum);
        }
        
        public System.Threading.Tasks.Task<string> checkNumberAsync(int userNum, int SecretNum) {
            return base.Channel.checkNumberAsync(userNum, SecretNum);
        }
    }
}
