//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkflowConsoleApplication1.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService")]
    public interface IService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/Encrypt", ReplyAction="http://tempuri.org/IService/EncryptResponse")]
        WorkflowConsoleApplication1.ServiceReference1.EncryptResponse Encrypt(WorkflowConsoleApplication1.ServiceReference1.EncryptRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/Encrypt", ReplyAction="http://tempuri.org/IService/EncryptResponse")]
        System.Threading.Tasks.Task<WorkflowConsoleApplication1.ServiceReference1.EncryptResponse> EncryptAsync(WorkflowConsoleApplication1.ServiceReference1.EncryptRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/Decrypt", ReplyAction="http://tempuri.org/IService/DecryptResponse")]
        WorkflowConsoleApplication1.ServiceReference1.DecryptResponse Decrypt(WorkflowConsoleApplication1.ServiceReference1.DecryptRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/Decrypt", ReplyAction="http://tempuri.org/IService/DecryptResponse")]
        System.Threading.Tasks.Task<WorkflowConsoleApplication1.ServiceReference1.DecryptResponse> DecryptAsync(WorkflowConsoleApplication1.ServiceReference1.DecryptRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Encrypt", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class EncryptRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string text;
        
        public EncryptRequest() {
        }
        
        public EncryptRequest(string text) {
            this.text = text;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="EncryptResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class EncryptResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string EncryptResult;
        
        public EncryptResponse() {
        }
        
        public EncryptResponse(string EncryptResult) {
            this.EncryptResult = EncryptResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Decrypt", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class DecryptRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string text;
        
        public DecryptRequest() {
        }
        
        public DecryptRequest(string text) {
            this.text = text;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DecryptResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class DecryptResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string DecryptResult;
        
        public DecryptResponse() {
        }
        
        public DecryptResponse(string DecryptResult) {
            this.DecryptResult = DecryptResult;
        }
    }
}
